<a href="https://colab.research.google.com/github/ivettke/Pyhon_course_Library_Juice/blob/main/Week_1_Homework_ipynb_copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://flonnesan.github.io/Sinapupunan/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Gusto Kita with All My Hypothalamus",
  "creator": "Dwein Baltazar",
  "date": "2018-05-09",
  "description": "In Avenida, the lives of four men intertwine, searching for something. They all find what they are looking for in one woman named Aileen.",
  "format": "image/jpeg",
  "language": "fil",
  "rights": "Public domain",
  "reference_url": "https://flonnesan.github.io/Sinapupunan/item.html?id=snsp017"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://flonnesan.github.io/Sinapupunan/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {}
    },
    {
      "field": "creator",
      "terms": {
        "alyx arumpac": 1,
        "antoinette jadaone": 3,
        "cathy garcia-molina": 3,
        "dwein baltazar": 3,
        "hannah espia": 3,
        "isabel sandoval": 3,
        "joyce bernal": 3,
        "olivia lamasan": 3,
        "ramona diaz": 3,
        "sari dalena": 3
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 26,
        "image/png": 2
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- facet 1 subject
- facet 2 creator
- facet 3 format
- ...

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below


This facet that shows up the most is *format* it is used *26* times on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized= pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,format,language,rights,reference_url
0,Fan Girl,Antoinette Jadaone,2020-10-31,After stowing away in the back of his onscreen...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
1,Six Degrees of Separation from Lilia Cuntapay,Antoinette Jadaone,2012-10-31,"In this mockumentary, Jadaone gives the iconic...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
2,That Thing Called Tadhana,Antoinette Jadaone,2015-02-04,A broken-hearted woman struggling to meet airl...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
3,Transit,Hannah Espia,2013-07-02,"Moises, a single Filipino dad, comes home to c...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
4,Ruweda,Hannah Espia,2012-07-21,Three people cross paths at a local town carni...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
5,Mamang Pulis,Hannah Espia,2012-12-18,"UP Film Institute’s property custodian, Kuya C...",image/png,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
6,Lingua Franca,Isabel Sandoval,2019-09-06,"Olivia, an undocumented Filipina immigrant par...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
7,Aparisyon,Isabel Sandoval,2012-07-21,"Tucked away in a remote forest, the convent of...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
8,Señorita,Isabel Sandoval,2011-08-06,A transgender woman tries to leave sex work by...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
9,Aswang,Alyx Arumpac,2019-11-21,Aswang follows a group of people whose lives h...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
10,A Thousand Cuts,Ramona Diaz,2020-01-25,A look at how Philippine President Rodrigo Dut...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
11,Motherland,Ramona Diaz,2017-01-21,Taking us into the heart of the planet's busie...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
12,Imelda,Ramona Diaz,2004-07-20,Follows the rise of a Filipino political dynas...,image/png,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
13,In My Life,Olivia Lamasan,2009-09-16,Shirley is a woman who wants to be in control ...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
14,The Mistress,Olivia Lamasan,2012-09-12,A young woman is torn between the affections o...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
15,In the Name of Love,Olivia Lamasan,2011-05-11,Former dance instructor Emman Toledo was emplo...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
16,Gusto Kita with All My Hypothalamus,Dwein Baltazar,2018-05-09,"In Avenida, the lives of four men intertwine, ...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
17,Oda sa Wala,Dwein Baltazar,2018-10-23,"Sonya, an old maid is about to give up on hers...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
18,Mamay Umeng,Dwein Baltazar,2012-11-30,"In a quaint provincial town, an elderly man aw...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
19,Ka Oryang,Sari Dalena,2011-11-11,A young woman witnesses the beginnings of a re...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
20,The Guerilla Is a Poet,Sari Dalena,2013-09-18,The tale of an activist's journey during the t...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
21,Dahling Nick,Sari Dalena,2015-11-09,"The story of Nick Joaquin, who only accepted t...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
22,10000 Hours,Joyce Bernal,2013-12-25,Senator Gabriel Alcaraz is preparing to delive...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
23,Kimmy Dora: Kambal sa Kiyeme,Joyce Bernal,2009-09-02,Kimmy and Dora (both Eugene Domingo) are ident...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
24,Everything About Her,Joyce Bernal,2016-01-27,"Powerful but ill-stricken business woman, Vilm...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
25,"Hello, Love, Goodbye",Cathy Garcia-Molina,2019-07-31,A bartender and a domestic helper of Filipino ...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
26,One More Chance,Cathy Garcia-Molina,2002-11-17,Popoy and Basha had been together forever. The...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
27,It Takes a Man and a Woman,Cathy Garcia-Molina,2013-03-30,The film follows the life of Miggy and Laida a...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,creator,date,description,format,language,rights,reference_url
24,Everything About Her,Joyce Bernal,2016-01-27,"Powerful but ill-stricken business woman, Vilm...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
2,That Thing Called Tadhana,Antoinette Jadaone,2015-02-04,A broken-hearted woman struggling to meet airl...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
6,Lingua Franca,Isabel Sandoval,2019-09-06,"Olivia, an undocumented Filipina immigrant par...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
3,Transit,Hannah Espia,2013-07-02,"Moises, a single Filipino dad, comes home to c...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
17,Oda sa Wala,Dwein Baltazar,2018-10-23,"Sonya, an old maid is about to give up on hers...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
1,Six Degrees of Separation from Lilia Cuntapay,Antoinette Jadaone,2012-10-31,"In this mockumentary, Jadaone gives the iconic...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
7,Aparisyon,Isabel Sandoval,2012-07-21,"Tucked away in a remote forest, the convent of...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
5,Mamang Pulis,Hannah Espia,2012-12-18,"UP Film Institute’s property custodian, Kuya C...",image/png,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
25,"Hello, Love, Goodbye",Cathy Garcia-Molina,2019-07-31,A bartender and a domestic helper of Filipino ...,image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...
18,Mamay Umeng,Dwein Baltazar,2012-11-30,"In a quaint provincial town, an elderly man aw...",image/jpeg,fil,Public domain,https://flonnesan.github.io/Sinapupunan/item.h...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
cb_normalized[cb_normalized["format"] == "terms"].count()

title            0
creator          0
date             0
description      0
format           0
language         0
rights           0
reference_url    0
dtype: int64


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.